name: cmdBook
main: VdW.Maxim.cmdBook.cmdBook
version: 1.0.2
website: http://dev.bukkit.org/server-mods/cmdBook/
author: Maximvdw
description: Execute multiple commands in a book
commands:
  cmdbook:
    description: Utilize the plugin
  cb:
    description: Utilize the plugin

permissions:
    cmdbook.*:
        description: Gives access to all cmdBook commands
        default: op
        children:
            cmdbook.about: true
            cmdbook.help: true
            cmdbook.edit: true
            cmdbook.create: true
            cmdbook.info: true
    cmdbook.help:
        description: Allows a user to see the help menu
        default: true
    cmdbook.about:
        description: Allows a user to see more information about the plugin
        default: true
    cmdbook.create:
        description: Allows the user to create a cmdBook
        default: op
    cmdbook.edit:
        description: Allows a user to edit a cmdBook
        default: op
    cmdbook.info:
        description: Allows a user to see the commands inside a book
        default: op