name: cmdBook
main: VdW.Maxim.cmdBook.cmdBook
version: 1.3.0
website: http://dev.bukkit.org/server-mods/cmdBook/
author: Maximvdw
description: Execute multiple commands in a book
commands:
  cb:
    description: Utilize the plugin
permissions:
    cmdbook.administrator:
        description: Administrators can do anything
        default: op
        children:
           cmdbook.*: true
    cmdbook.moderator:
        description: Moderators can use better cmdBooks and read all books
        default: op
        children:
           cmdbook.use: true
           cmdbook.about: true
           cmdbook.help: true
           cmdbook.private.own: true
           cmdbook.public.own: true
           cmdbook.variable.runconsole: true
           cmdbook.variable.hidemessages: true
           cmdbook.input: true
           cmdbook.calculation: true
           cmdbook.javascript: true
           cmdbook.create: false
           cmdbook.readall: true
    cmdbook.user:
        description: Users can use cmdBooks, but not create them
        default: op
        children:
           cmdbook.use: true
           cmdbook.about: true
           cmdbook.help: true
           cmdbook.private.own: true
           cmdbook.public.own: true
           cmdbook.variable.runconsole: true
           cmdbook.variable.hidemessages: true
           cmdbook.input: true
           cmdbook.calculation: true
           cmdbook.javascript: false
           cmdbook.create: false
    cmdbook.*:
        description: Gives access to all cmdBook commands
        default: op
        children:
            cmdbook.use: true
            cmdbook.about: true
            cmdbook.help: true
            cmdbook.edit: true
            cmdbook.create: true
            cmdbook.info: true
            cmdbook.variable.player: true
            cmdbook.variable.targetplayer: true
            cmdbook.variable.health: true
            cmdbook.variable.xp: true
            cmdbook.variable.targetxp: true
            cmdbook.variable.lvl: true
            cmdbook.variable.targetlvl: true
            cmdbook.variable.hunger: true
            cmdbook.variable.targethunger: true
            cmdbook.variable.killer: true
            cmdbook.variable.targetkiller: true
            cmdbook.variable.xpos: true
            cmdbook.variable.ypos: true
            cmdbook.variable.targetxpos: true
            cmdbook.variable.targetypos: true
            cmdbook.variable.losx: true
            cmdbook.variable.losy: true
            cmdbook.variable.losz: true
            cmdbook.readall: true
            cmdbook.private.own: true
            cmdbook.public.own: true
            cmdbook.private.all: true
            cmdbook.public.all: true
            cmdbook.variable.runconsole: true
            cmdbook.variable.hidemessages: true
            cmdbook.reload: true
            cmdbook.input: true
            cmdbook.calculation: true
            cmdbook.javascript: true
    cmdbook.use:
        description: Allows a user to use a cmdBook
        default: true
    cmdbook.help:
        description: Allows a user to see the help menu
        default: true
    cmdbook.about:
        description: Allows a user to see more information about the plugin
        default: true
    cmdbook.create:
        description: Allows the user to create a cmdBook
        default: op
    cmdbook.edit:
        description: Allows a user to edit a cmdBook
        default: op
    cmdbook.info:
        description: Allows a user to see the commands inside a book
        default: op
    cmdbook.variable.player:
        description: Allows a user to use the $player variable
        default: true
        children:
            cmdbook.use.player: true
    cmdbook.variable.targetplayer:
        description: Allows a user to use the $targetplayer variable
        default: true
        children:
            cmdbook.use.targetplayer: true
    cmdbook.variable.health:
        description: Allows a user to use the $health variable
        default: true
        children:
            cmdbook.use.health: true
    cmdbook.variable.xp:
        description: Allows a user to use the $xp variable
        default: true
        children:
            cmdbook.use.xp: true
    cmdbook.variable.targetxp:
        description: Allows a user to use the $targetxp variable
        default: true
        children:
            cmdbook.use.targetxp: true
    cmdbook.variable.lvl:
        description: Allows a user to use the $targetxp variable
        default: true
        children:
            cmdbook.use.lvl: true
    cmdbook.variable.targetlvl:
        description: Allows a user to use the $targetlvl variable
        default: true
        children:
            cmdbook.use.targetlvl: true
    cmdbook.variable.hunger:
        description: Allows a user to use the $hunger variable
        default: true
        children:
            cmdbook.use.hunger: true
    cmdbook.variable.targethunger:
        description: Allows a user to use the $targethunger variable
        default: true
        children:
            cmdbook.use.targethunger: true
    cmdbook.variable.killer:
        description: Allows a user to use the $killer variable
        default: true
        children:
            cmdbook.use.killer: true
    cmdbook.variable.targetkiller:
        description: Allows a user to use the $targetkiller variable
        default: true
        children:
            cmdbook.use.targetkiller: true
    cmdbook.variable.xpos:
        description: Gets your Xpos
        default: true    
    cmdbook.variable.ypos:
        description: Gets your Ypos
        default: true 
    cmdbook.variable.targetxpos:
        description: Gets your targets Xpos
        default: true    
    cmdbook.variable.targetypos:
        description: Gets your targets Ypos
        default: true
    cmdbook.variable.losx:
        description: Gets the location (x) of the block you are looking at
        default: true
    cmdbook.variable.losy:
        description: Gets the location (y) of the block you are looking at
        default: true
    cmdbook.variable.losz:
        description: Gets the location (z) of the block you are looking at
        default: true
    cmdbook.variable.runconsole:
        description: Let the console run the commands
        default: op
    cmdbook.variable.hidemessages:
        description: Hide cmdBook messages
        default: op
    cmdbook.readall:
        description: Lets you read all protected books
        default: op
    cmdbook.private.own:
        description: Lets a user private his own book
        default: true
    cmdbook.public.own:
        description: Lets a user unprivate his own book
        default: true
    cmdbook.private.all:
        description: Lets a user private all books
        default: op
    cmdbook.public.all:
        description: Lets a user unprivate all books
        default: op
    cmdbook.reload:
        description: Reload configuration
        default: op