name: cmdBook
main: VdW.Maxim.cmdBook.cmdBook
version: 1.3.0
website: http://dev.bukkit.org/server-mods/cmdBook/
author: Maximvdw
description: Execute multiple commands in a book
commands:
  cb:
    description: Utilize the plugin
permissions:
    cmdbook.*:
        description: Gives access to all cmdBook commands
        default: op
        children:
            cmdbook.about: true
            cmdbook.help: true
            cmdbook.edit: true
            cmdbook.create: true
            cmdbook.info: true
            cmdbook.variable.player: true
            cmdbook.variable.targetplayer: true
            cmdbook.variable.health: true
            cmdbook.variable.xp: true
            cmdbook.variable.targetxp: true
            cmdbook.variable.lvl: true
            cmdbook.variable.targetlvl: true
            cmdbook.variable.hunger: true
            cmdbook.variable.targethunger: true
            cmdbook.variable.killer: true
            cmdbook.variable.targetkiller: true
            cmdbook.variable.xpos: true
            cmdbook.variable.ypos: true
            cmdbook.variable.targetxpos: true
            cmdbook.variable.targetypos: true
            cmdbook.readall: true
    cmdbook.help:
        description: Allows a user to see the help menu
        default: true
    cmdbook.about:
        description: Allows a user to see more information about the plugin
        default: true
    cmdbook.create:
        description: Allows the user to create a cmdBook
        default: op
    cmdbook.edit:
        description: Allows a user to edit a cmdBook
        default: op
    cmdbook.info:
        description: Allows a user to see the commands inside a book
        default: op
    cmdbook.variable.player:
        description: Allows a user to use the $player variable
        default: true
    cmdbook.variable.targetplayer:
        description: Allows a user to use the $targetplayer variable
        default: true
    cmdbook.variable.health:
        description: Allows a user to use the $health variable
        default: true
    cmdbook.variable.xp:
        description: Allows a user to use the $xp variable
        default: true
    cmdbook.variable.targetxp:
        description: Allows a user to use the $targetxp variable
        default: true
    cmdbook.variable.lvl:
        description: Allows a user to use the $targetxp variable
        default: true
    cmdbook.variable.targetlvl:
        description: Allows a user to use the $targetlvl variable
        default: true
    cmdbook.variable.hunger:
        description: Allows a user to use the $hunger variable
        default: true
    cmdbook.variable.targethunger:
        description: Allows a user to use the $targethunger variable
        default: true
    cmdbook.variable.killer:
        description: Allows a user to use the $killer variable
        default: true
    cmdbook.variable.targetkiller:
        description: Allows a user to use the $targetkiller variable
        default: true
    cmdbook.variable.xpos:
        description: Gets your Xpos
        default: true    
    cmdbook.variable.ypos:
        description: Gets your Ypos
        default: true 
    cmdbook.variable.targetxpos:
        description: Gets your targets Xpos
        default: true    
    cmdbook.variable.targetypos:
        description: Gets your targets Ypos
        default: true
    cmdbook.readall:
        description: Lets you read all protected books
        default: op